accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (
  login_view, 
  register_view, 
  profile_detail_view,
  logout_view,
  edit_profile
)
app_name = 'accounts'

urlpatterns = [
  path('', login_view, name='login-view'),





  path('accounts/logout/', logout_view, name='logout-view'),
  path('accounts/register/', register_view, name='register'),
  path('accounts/edit-profile/', edit_profile, name='edit-profile'),
  path('accounts/<slug>/', profile_detail_view, name='profile-detail-view'),

  

  

]

# Password reset 
# 1 - submit email form 
# 2 - email sent success message
# 3 - link to password reset form in email
# 4 - Passwrod successfully change message

blog/urls.py
from django.urls import path
from .views import (
  home_view, 
  my_recipes_view,
  create_recipe,
  main_view,
  recipe_detail,
  edit_recipe,
  delete_recipe,
  draft_view, 
  edit_recipe_draft,
  delete_recipe_draft,
  search_recipes,
  category_view,
  about_view,
)

app_name = 'blog'

urlpatterns = [
  path('', main_view, name='main-view'),
  path('myrecipes/', my_recipes_view, name='myrecipes-view'),
  path('create-recipe/', create_recipe, name='create-recipe'),
  path('recipe-detail/<slug>/', recipe_detail, name='recipe-detail'),
  path('edit-recipe/<slug>/', edit_recipe, name='edit-recipe'),
  path('delete-recipe/<slug>/', delete_recipe, name='delete-recipe'),
  path('draft-view/', draft_view, name='draft-view'),

  path('edit-draft/<slug>', edit_recipe_draft, name='edit-draft'),
  path('delete-draft/<slug>', delete_recipe_draft, name='delete-draft'),
  path('search-recipes/', search_recipes, name='search-recipes'),
  path('category/<cats>/', category_view, name='category-view'),
  path('about/', about_view, name='about-view'),
  #path('rate-recipe/slug/', rate, name='rate-recipe'),
  #path('submit-review/<int:recipe_id>/', submit_review, name='submit-review'),
]

myrecipe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .forms import UserPasswordResetForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),

#password reset
  path('reset_password/', 
    auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        form_class=UserPasswordResetForm,
        ), 
    name='reset_password'),

  path('reset_password_sent/', 
    auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'), 
    name='password_reset_done'),

  path('reset/<uidb64>/<token>', 
    auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'), 
    name='password_reset_confirm'),

  path('reset_password_complete/', 
    auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'), 
    name='password_reset_complete'),

    path('blog/', include('blog.urls', namespace='blog')),

    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.template.defaultfilters import slugify
from .utils import get_random_code
from django.urls import reverse


# SOCIAL_CHOICES = (
#   #db          #frontend 
#   'facebook', 'facebook',
#   'instagram', 'instagram',
#   'pinterest', 'pinterest',
#   'twitter', 'twitter',
# )

class Profile(models.Model):
  first_name = models.CharField(max_length=200, blank=True)
  last_name = models.CharField(max_length=200, blank=True)
  avatar = models.ImageField(default='avatar.jpg', upload_to='avatars/')
  slug = models.SlugField(max_length=200, unique=True)
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  website = models.URLField(max_length=50, blank=True)
  location = models.CharField(max_length=200, blank=True)
  bio = models.TextField(max_length=200, blank=True)
  email = models.EmailField(max_length=200, blank=True)
  facebook = models.CharField(max_length=200, blank=True)
  twitter = models.CharField(max_length=200, blank=True)
  instagram = models.CharField(max_length=200, blank=True)
  pinterest = models.CharField(max_length=200, blank=True)
  others = models.CharField(max_length=200, blank=True)
  updated = models.DateTimeField(auto_now=True)
  created = models.DateTimeField(auto_now_add=True)

  class Meta:
    ordering = ('-created',)

  def __str__(self):
    return str(self.user)
  
  #profile detail slug
  def get_absolute_url(self):
    return reverse('accounts:profile-detail-view', kwargs={'slug': self.slug})
  
  #generate slug
  # def save(self, *args, **kwargs):
  #   ex = False

  #   #if fname & lname exist
  #   if self.first_name and self.last_name:
  #     to_slug = slugify(str(self.first_name) + " " + str(self.last_name))

  #     #return true
  #     ex = Profile.objects.filter(slug=to_slug).exists()

  #     #if slug exists
  #     while ex:
  #       to_slug = slugify(to_slug + " " + str(get_random_code()))
  #       ex = Profile.objects.filter(slug=to_slug).exists()

  #   #if fname & lname blank
  #   else:
  #     to_slug = str(self.user)
  #   self.slug = to_slug
  #   super().save(*args, **kwargs)

  
  

accounts/forms.py
from django import forms
from .models import Profile
    


class RegisterForm(forms.Form):
  first_name = forms.CharField(max_length=100)
  last_name = forms.CharField(max_length=100)
  user_name = forms.CharField(max_length=100)
  email = forms.EmailField(max_length=100)
  password = forms.CharField(widget=forms.PasswordInput())
  confirm_password = forms.CharField(widget=forms.PasswordInput())


class EditProfileForm(forms.ModelForm):
  avatar = forms.ImageField(widget=forms.FileInput)
  class Meta:
    model = Profile
    fields = ('first_name', 'last_name', 'avatar', 'website', 'location', 'bio', 'email', 'facebook', 'twitter', 'pinterest', 'instagram')

accounts/views.py
from django.shortcuts import render, redirect
from .models import Profile
from blog.models import Post, Review
from django.contrib.auth.models import User 
from django.template.defaultfilters import slugify
from .forms import RegisterForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import get_object_or_404
from .forms import EditProfileForm
from django.db.models import Q
from random import randint


def login_view(request):
  recipes = Post.objects.filter(Q(featured=True) & Q(status='published'))
  # random_num = randint(0, len(recipes)-1)

  #random recipe featured
  # recipe_featured = Post.objects.filter(featured=True)[random_num]
  recipe_featured = Post.objects.filter(Q(featured=True) & Q(status='published'))
  recipe_published = Post.objects.filter(status='published')


  # print(recipe_featured)
  # user_recipe = recipe_featured.photo.url
  # profile_image = recipe_featured.author.avatar.url
  # profile_name = recipe_featured.author.user

  # print(user_recipe)
  # print(recipe_featured.author)
  if request.user.is_authenticated:
    return redirect('blog:main-view')
  else:
    if request.method == 'POST':
      user_name = request.POST['username']
      password = request.POST['password']

      user = authenticate(username=user_name, password=password)
      if user is not None:
        login(request, user)
        return redirect('blog:main-view')
      else:
        messages.error(request, 'Invalid credentials')
        return redirect('accounts:login-view')

  print(recipe_featured)
      
  context = {
    'recipes': recipes,
    'recipe_featured': recipe_featured,
    # 'profile_image': profile_image,
    # 'profile_name': profile_name,
    # 'user_recipe': user_recipe,
    'recipe_published': recipe_published,
  }


  return render(request, 'accounts/login.html', context)




@login_required(login_url="/")
def logout_view(request):
  logout(request)
  return redirect('accounts:login-view')



def register_view(request):
  if request.user.is_authenticated:
    return redirect('accounts:main-view')
  else:
  
    if request.method == 'POST':
      
      first_name = request.POST['firstname']
      last_name = request.POST['lastname']
      user_name = request.POST['username']
      email = request.POST['email']
      password = request.POST['password1']
      confirm_password = request.POST['password2']

      to_slug = f"{first_name}-{last_name}"

      if password == confirm_password:
        #check if username and email exists
        if User.objects.filter(username=user_name).exists():
          #username already exists
          messages.error(request, 'Username already exists')
          return redirect('accounts:register')
        else:
          if User.objects.filter(email=email).exists():
            #email already exists
            messages.error(request, 'Email already exists')
            return redirect('accounts:register')
          else:
            
            #*if valid
            
            # create User object
            user = User.objects.create_user(
              first_name=first_name,
              last_name=last_name,
              username=user_name,
              email=email,
              password=password,
            )

            # create Profile for User
            user_profile = Profile.objects.create(
              first_name=first_name,
              last_name=last_name,
              slug=to_slug,
              user=user,
            )
            
            user.save()
            #user_profile.save()
            messages.warning(request, 'Account Registered for ' + str(user))
            return redirect('accounts:login-view')
      else:
        messages.error(request, 'Password do not match')
        return redirect('accounts:register')
      
  return render(request, 'accounts/register.html')





  
# @login_required(login_url="/")
def profile_detail_view(request, slug):
  profile = get_object_or_404(Profile, slug=slug)
  # current_user = Profile.objects.get(user=request.user)
  # myrecipes = Post.objects.filter(author=current_user)

  all_reviews = []
 

  #display all recipes except current user
  all_recipes = Post.objects.filter(Q(status='published') & Q(author=profile))
  recipe_published = Post.objects.filter(Q(status='published') & Q(author=profile))
  reviews = Post.objects.filter(Q(status='published') & Q(author=profile) & Q(reviews__isnull=False))
  recipe_count = all_recipes.count()
  
  #*GET USER REVIEWS
  #loop tru all published recipes of user
  for recipe in recipe_published:
    all_reviews.append(recipe.reviews.all())

  #loop tru recipe has a review and review count (queryset.count())
  #delete empty queryset
  all_reviews_result = [reviews.count() for reviews in all_reviews if reviews]

  #get all user recipe reviews count
  user_reviews_count = sum(all_reviews_result)

  # print(all_reviews)
  # print(all_reviews_result)
  # print(user_reviews_count)


  #*GET USER RATING
  for recipe in recipe_published:
    all_reviews.append(recipe.reviews.all())
  
  all_avg_review = [reviews.average_review() for reviews in recipe_published]
  #delete empty queryset
  all_avg_review_result = [reviews for reviews in all_avg_review if reviews]
  
  try:
    get_avg_review = (sum(all_avg_review_result) / len(all_avg_review_result))
  except ZeroDivisionError:
    get_avg_review = 0

  get_count_review = len(all_avg_review_result)

  # print(all_avg_review)
  # print(all_avg_review_result)
  # print(get_avg_review)
  print(get_count_review)

  context = {
    'profile': profile,
    'recipe_count': recipe_count,
    'all_recipes': all_recipes,
    'recipe_published': recipe_published,
    'user_reviews_count': user_reviews_count,
    'get_avg_review': get_avg_review,
    'get_count_review': get_count_review,
  }

  return render(request, 'accounts/profile.html', context)



@login_required(login_url="/")
def edit_profile(request):
  #get profile of current logged in user
  user_profile = Profile.objects.get(user=request.user)
  
  if request.method == 'POST':
    edit_profile_form = EditProfileForm(request.POST, request.FILES, instance=user_profile)
    if edit_profile_form.is_valid():
      edit_profile_form.save()
      return redirect('accounts:profile-detail-view', slug=user_profile.slug)
  else:
    #form with prefilled info
    edit_profile_form = EditProfileForm(instance=user_profile)
    
  context = {'form': edit_profile_form}
  
  return render(request, 'accounts/edit_profile.html', context)

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}


{% block title %}
  main
{% endblock title %}



{% block content %}
<!-- MAIN PAGE -->
<div class="main-page-header">
  <div class="container">
    <div id="editprofile-page">

      
      <!-- Register -->
        <div id="editprofile-form">
          <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>Update Profile</h1>

            <label for="">First Name</label>
            {{form.first_name}}

            <label for="">Last Name</label>
            {{form.last_name}}

            <label for="">Avatar</label>
            {{form.avatar}}

            <label for="">Website</label>
            {{form.website}}

            <label for="">Location</label>
            {{form.location}}

            <label for="">Bio</label>
            {{form.bio}}

            <label for="">Email</label>
            {{form.email}}

            <label for="">Facebook</label>
            {{form.facebook}}

            <label for="">Twitter</label>
            {{form.twitter}}

            <label for="">Pinterest</label>
            {{form.pinterest}}

            <label for="">Instagram</label>
            {{form.instagram}}

            <div class="inputs2">
              <button type="submit">Update</button>
            </div>
            
          </form>
        </div>


    </div>
  </div>
</div>
{% endblock content %}
  

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  MyRecipe | login
{% endblock title %}
  

{% block content %}
  <!-- MAIN PAGE -->
  <div class="main-page-header">
    <div class="container">
      <div id="main-page">
  
        <div class="left">
          
          {% for recipe in recipe_featured %}
            {% if recipe_featured %}
            <!-- Featured -->
          <div id="featured" class="slider fade">
            <h1>Featured</h1>
            <div class="recipe-img">
              <img src="{{ recipe.photo.url }}" alt="">
            </div>
            
            <div class="description">
              <div class="time">
                <div class="clock">
                  <i class="far fa-clock clock"></i>{{ recipe.cooking_time }}
                </div>
                <!-- <div>
                  <a href="#"class="like">Like</a>
                </div> -->
                
                {% if recipe.average_review %}
                <div class="rating-star">
                  <span>
                    <i class="fa fa-star{% if recipe.average_review < 0.5 %}-o{% elif recipe.average_review >= 0.5 and recipe.average_review < 1 %}-half-alt {% endif %}"></i>
                    <i class="fa fa-star{% if recipe.average_review < 1.5 %}-o{% elif recipe.average_review >= 1.5 and recipe.average_review < 2 %}-half-alt {% endif %}"></i>
                    <i class="fa fa-star{% if recipe.average_review < 2.5 %}-o{% elif recipe.average_review >= 2.5 and recipe.average_review < 3 %}-half-alt {% endif %}"></i>
                   <i class="fa fa-star{% if recipe.average_review < 3.5 %}-o{% elif recipe.average_review >= 3.5 and recipe.average_review < 4 %}-half-alt {% endif %}"></i>
                   <i class="fa fa-star{% if recipe.average_review < 4.5 %}-o{% elif recipe.average_review >= 4.5 and recipe.average_review < 5 %}-half-alt {% endif %}"></i>
 
                 </span>
               </div>
             {% else %}
               <div class="rating-star">
                 <span>
                   <i class="fa fa-star-o"></i>
                   <i class="fa fa-star-o"></i>
                   <i class="fa fa-star-o"></i>
                   <i class="fa fa-star-o"></i>
                   <i class="fa fa-star-o"></i>
                 </span>
               </div>
             {% endif %}
             </div>
             <a href="{% url 'blog:recipe-detail' recipe.slug %}"><h2>{{ recipe.title }}</h2></a>
           
             <p>{{ recipe.description|truncatechars:"50" }}</p>
   
             <div class="user">
               
               <a href="{% url 'accounts:profile-detail-view' recipe.author.slug %}">
                 <div class="user-img">
                   <img src="{{ recipe.author.avatar.url }}" alt="">
                 </div>
               </a>
               
               <div class="user-info">
                 <h3>{{ recipe.author.user }}</h3>
                 <p class="date">{{ recipe.created | timesince }}</p>
               </div>
             </div>
           </div>
   
         </div>
       
          {% else %}
            <h1>No Data</h1>
          {% endif %}
        {% endfor %}
            
          

        </div>
        <!-- end left -->
       
        
        <!-- Login -->
        <div class="right" id="login">
          <div id="login-form">
            {% if messages %}
            
            {% for message in messages %}
            <div style="color: tomato;">{{ message }}</div>
            {% endfor %}

          {% endif %}
            
            <form method="POST">

              {% csrf_token %}
              <h1>Login</h1>
              
              <div class="inputs1">
                <label for="username">Username</label>
                <input type="text" name="username" placeholder="User Name*" id="username">
                <label for="password">Password</label>

                <div class="input-box">
                  <input type="password" name="password" placeholder="Password*" id="password" class="password-toggle">
                  <div class='toggle-eye-crossed'></div>
                </div>
                
              </div>
  
              <div class="inputs2">
                <button type="submit">Login</button>
                <a href="{% url 'reset_password' %}" class="forgot">Forgot Password?</a>
              </div>

            </form>
          </div>
          <div class="underline"></div>
          <a href="{% url 'accounts:register' %}" class="register">Create New Account</a>
        </div>
        <!-- end right -->
  
      </div>
       <!-- End Main Page  -->

    </div>
  </div>

  <section id="recipes-section">
    <div class="container">
      <section id="recipes">
        <h1>Recipes</h1>
    
        <div class="recipe-cards"'>
          
          
          {% if recipes %}
            {% for recipe in recipe_published %}
            <!-- recipe card -->
            <div class="recipe-card">
              <div class="recipe-img">
                <img src="{{ recipe.photo.url }}" alt="">
              </div>
              
              <div class="description">
                <div class="time">
                  <div class="clock">
                    <i class="far fa-clock clock" style="color: #001433;"></i>
                     <span style="color: #787878;">{{ recipe.cooking_time }}</span>
                  </div>
                  <!-- <div><a href="#">Like</a></div> -->
                  {% if recipe.average_review %}
                  <div class="rating-star">
                    <span>
                      <i class="fa fa-star{% if recipe.average_review < 0.5 %}-o{% elif recipe.average_review >= 0.5 and recipe.average_review < 1 %}-half-alt {% endif %}"></i>
                      <i class="fa fa-star{% if recipe.average_review < 1.5 %}-o{% elif recipe.average_review >= 1.5 and recipe.average_review < 2 %}-half-alt {% endif %}"></i>
                      <i class="fa fa-star{% if recipe.average_review < 2.5 %}-o{% elif recipe.average_review >= 2.5 and recipe.average_review < 3 %}-half-alt {% endif %}"></i>
                      <i class="fa fa-star{% if recipe.average_review < 3.5 %}-o{% elif recipe.average_review >= 3.5 and recipe.average_review < 4 %}-half-alt {% endif %}"></i>
                      <i class="fa fa-star{% if recipe.average_review < 4.5 %}-o{% elif recipe.average_review >= 4.5 and recipe.average_review < 5 %}-half-alt {% endif %}"></i>
    
                    </span>
                  </div>
                  {% else %}
                  <div class="rating-star">
                    <span>
                      <i class="fa fa-star-o"></i>
                      <i class="fa fa-star-o"></i>
                      <i class="fa fa-star-o"></i>
                      <i class="fa fa-star-o"></i>
                      <i class="fa fa-star-o"></i>
    
    
                    </span>
                  </div>
                  {% endif %}
                </div>
                
                <a href="{% url 'blog:recipe-detail' recipe.slug %}"><h2>{{ recipe.title }}</h2></a>
              
              <p style="margin-bottom: 2rem;">{{ recipe.description | truncatechars:50  }}</p>
    
              <div class="user">
                
                <a href="{% url 'accounts:profile-detail-view' recipe.author.slug %}">
                  <div class="user-img">
                    <img src="{{ recipe.author.avatar.url }}" alt="">
                  </div>
                </a>
                
                <div class="user-info">
                  <h3>{{ recipe.author.user }}</h3>
                  <p class="date">April 30, 2021</p>
                </div>
              </div>
              </div>
          </div>
          <!-- end recipe card -->
          {% endfor %}
          {% else %}
          <h1>No Data</h1>
          {% endif %}
            
          
            
          
    
        </div>
      </section>
    </div>
  </section>

  <script>
    
  </script>
  
{% endblock content %}
  

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}


{% block title %}
  main
{% endblock title %}


{% block content %}
  <!-- MAIN CONTENT -->

  <!-- PROFILE -->
  <div class="container" id="profile">
      
    <h1 class="profile-heading">Profile</h1>
    <div id="profile-section">
      <div class="about-me">
        <h3>About Me</h3>
        <div class="profile-img">


          <img src="{{ profile.avatar.url }}" alt="">

            
          
        </div>
        <div class="profile-name">
          <p>{{ profile.first_name|title }} {{ profile.last_name|title }}</p>
        </div>
        <div class="website">
          <a href="{{ profile.website }}" target="_blank"><p>{{ profile.website }}</p></a>
        </div>
        <div class="location">
          <p>{{ profile.location }}</p>
        </div>
        <div class="description">
          <p>{{ profile.bio}}</p>
        </div>
        <div class="socials">
          <a href="{{ profile.facebook }}" target="_blank">
            <i class="fab fa-facebook"></i>
          </a>
          <a href="{{ profile.twitter }}" target="_blank">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="{{ profile.instagram }}" target="_blank">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="{{ profile.pinterest }}" target="_blank">
            <i class="fab fa-pinterest"></i>
          </a>
        </a>
        </div>

        <!-- <div class="following">
          <a href="#">followers</a>
          <a href="#">following</a>
        </div> -->
      </div>

      <div class="profile-info">
        <div class="recipe-count">
          <h3>Recipes</h3>
            {% if profile.user == request.user %}
            <p>{{ recipe_count }}</p>
            {% else %}
            <p>{{ recipe_count }}</p>
            {% endif %}
        </div>
        <div class="like-count">
          <h3>Reviews</h3>
          <p>{{ user_reviews_count }}</p>
        </div>
        <div class="ratings-count">
          <h3>Rating</h3>
          <p>{{ get_avg_review|floatformat:"2" }}%</p>
        </div>
      </div>
     
    </div>
  </div>


    
    <!-- RECIPES -->
    <section id="recipes-section">
      <div class="container">
        <section id="recipes">
          <h1>Recipes</h1>
      
          <div class="recipe-cards">
            {% if profile.user == request.user and profile_recipe %}
              {% for recipe in profile_recipe %}
              <!-- recipe card -->
              <div class="recipe-card">
                <div class="recipe-img">
                  <img src="{{ recipe.photo.url }}" alt="">
                </div>
                
                <div class="description">
                  <div class="time">
                    <p>{{ recipe.cooking_time }}</p><a href="#">Like</a>
                    
  
                  </div>
                  
                  <a href="{% url 'blog:recipe-detail' recipe.slug %}"><h2>{{ recipe.title }}</h2></a>
                
                <p>{{ recipe.description }}</p>
        
                  <small style="color: #7A7A7E;">{{ recipe.created }}</small>
                </div>
              </div>
              <!-- end recipe card -->
              {% endfor %}
            {% else %}
              {% for recipe in recipe_published %}
              <!-- recipe card -->
              <div class="recipe-card">
                <div class="recipe-img">
                  <img src="{{ recipe.photo.url }}" alt="">
                </div>
                
                <div class="description">
                  <div class="time">
                    <div class="clock">
                      <i class="far fa-clock clock"></i>{{ recipe.cooking_time }}
                    </div>
                    <!-- <a href="#">Like</a> -->
                    {% if recipe.average_review %}
                    <div class="rating-star">
                      <span>
                        <i class="fa fa-star{% if recipe.average_review < 0.5 %}-o{% elif recipe.average_review >= 0.5 and recipe.average_review < 1 %}-half-alt {% endif %}"></i>
                        <i class="fa fa-star{% if recipe.average_review < 1.5 %}-o{% elif recipe.average_review >= 1.5 and recipe.average_review < 2 %}-half-alt {% endif %}"></i>
                        <i class="fa fa-star{% if recipe.average_review < 2.5 %}-o{% elif recipe.average_review >= 2.5 and recipe.average_review < 3 %}-half-alt {% endif %}"></i>
                        <i class="fa fa-star{% if recipe.average_review < 3.5 %}-o{% elif recipe.average_review >= 3.5 and recipe.average_review < 4 %}-half-alt {% endif %}"></i>
                        <i class="fa fa-star{% if recipe.average_review < 4.5 %}-o{% elif recipe.average_review >= 4.5 and recipe.average_review < 5 %}-half-alt {% endif %}"></i>
  
                      </span>
                    </div>
                    {% else %}
                    <div class="rating-star">
                      <span>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-o"></i>
                      </span>
                    </div>
                    {% endif %}
                  </div>
                  
                  <a href="{% url 'blog:recipe-detail' recipe.slug %}"><h2>{{ recipe.title }}</h2></a>
                
                <p>{{ recipe.description | truncatechars:50 }}</p>
        
                  <small style="color: #7A7A7E;">{{ recipe.created }}</small>
                </div>
              </div>
              <!-- end recipe card -->
              {% endfor %}
              
            {% endif %}
            
           
    
          </div>
        </section>
      </div>
  
    
    </section>
    

{% endblock content %}
  

accounts/templates/accounts/register.html
{% extends 'base.html' %}


{% block title %}
  register
{% endblock title %}
  

{% block content %}
<div class="main-page-header">
  <div class="container">
    <div id="register-page">
      
      
      <!-- Register -->
        <div id="register-form">
            
            {% if messages %}
            
              {% for message in messages %}
              <div style="color: tomato;">{{ message }}</div>
              {% endfor %}

            {% endif %}
              
          
          <form action="" method="POST" id="register-main-form">
            {% csrf_token %}
            <h1>Create an account</h1>

            <div class="inputs1">
              <div class="left">

                <label for="firstname">First Name</label>
                <input type="text" name="firstname" placeholder="First Name*" id="firstname">
                <div id="error"></div>


                <label for="lastname">Last Name</label>
                <input type="text" name="lastname" placeholder="Last Name*" id="lastname">
                <div id="error"></div>



                <label for="username">Username</label>
                <input type="text" name="username" placeholder="User Name*" id="username">
                <div id="error"></div>



              </div>
              
              <div class="right">
                <label for="email">Email</label>
                <input type="email" name="email" placeholder="Email*" id="email">
                <div id="error"></div>

                  

                
                <label for="password1">Password</label>
                <input type="password" name="password1" placeholder="Password*" id="password1">
                <div id="error"></div>


                <label for="password2">Confirm Password</label>
                <input type="password" name="password2" placeholder="Password*" id="password2">
                <div id="error"></div>


              </div>
            </div>
            

            <div class="inputs2"></div>
              <button type="submit">Register</button>
            </div>
            
          </form>
        </div>


    </div>
  </div>
</div>
{% endblock content %}
  