accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (
  login_view, 
  register_view, 
  profile_detail_view,
  logout_view,
  edit_profile
)
app_name = 'accounts'

urlpatterns = [
  path('', login_view, name='login-view'),





  path('accounts/logout/', logout_view, name='logout-view'),
  path('accounts/register/', register_view, name='register'),
  path('accounts/edit-profile/', edit_profile, name='edit-profile'),
  path('accounts/<slug>/', profile_detail_view, name='profile-detail-view'),

  

  

]

# Password reset 
# 1 - submit email form 
# 2 - email sent success message
# 3 - link to password reset form in email
# 4 - Passwrod successfully change message

blog/urls.py
from django.urls import path
from .views import (
  home_view, 
  my_recipes_view,
  create_recipe,
  main_view,
  recipe_detail,
  edit_recipe,
  delete_recipe,
  draft_view, 
  edit_recipe_draft,
  delete_recipe_draft,
  search_recipes,
  category_view,
  about_view,
)

app_name = 'blog'

urlpatterns = [
  path('', main_view, name='main-view'),
  path('myrecipes/', my_recipes_view, name='myrecipes-view'),
  path('create-recipe/', create_recipe, name='create-recipe'),
  path('recipe-detail/<slug>/', recipe_detail, name='recipe-detail'),
  path('edit-recipe/<slug>/', edit_recipe, name='edit-recipe'),
  path('delete-recipe/<slug>/', delete_recipe, name='delete-recipe'),
  path('draft-view/', draft_view, name='draft-view'),

  path('edit-draft/<slug>', edit_recipe_draft, name='edit-draft'),
  path('delete-draft/<slug>', delete_recipe_draft, name='delete-draft'),
  path('search-recipes/', search_recipes, name='search-recipes'),
  path('category/<cats>/', category_view, name='category-view'),
  path('about/', about_view, name='about-view'),
  #path('rate-recipe/slug/', rate, name='rate-recipe'),
  #path('submit-review/<int:recipe_id>/', submit_review, name='submit-review'),
]

myrecipe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .forms import UserPasswordResetForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),

#password reset
  path('reset_password/', 
    auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        form_class=UserPasswordResetForm,
        ), 
    name='reset_password'),

  path('reset_password_sent/', 
    auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'), 
    name='password_reset_done'),

  path('reset/<uidb64>/<token>', 
    auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'), 
    name='password_reset_confirm'),

  path('reset_password_complete/', 
    auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'), 
    name='password_reset_complete'),

    path('blog/', include('blog.urls', namespace='blog')),

    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
<!-- FOOTER -->
<div class="container">
  <footer>
    
      <div class="left">
        <p>Foodify</p>
      </div>
  
      <div class="center">
        <p>&copy; <span id="year"></span> Cristian To-ong</p>
      </div>
  
      <div class="right">
        <a href="#">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="#">
          <i class="fab fa-facebook"></i>
        </a>
        <a href="#">
          <i class="fab fa-pinterest"></i>
        </a>
      </div>
    
  </footer>

templates/includes/navbar.html
  <!-- NAV -->
{% load static %}
  <header>
    <div class="nav-full-width">
      <div class="container">
        <div id="nav1">
          <div class="logo">
            <a href="{% url 'blog:main-view' %}" style="color: #fff;">MyRecipe</a>
          </div>
  
          <div class="right search-nav">
            <form action="{% url 'blog:search-recipes' %}" method="POST">
              {% csrf_token %}
              <input type="text" placeholder="Search Recipes" name="searched">
              <button type="submit" class="search-btn">Search</button>
            </form>
          </div>

          <div class="mobile-menu">
            <span class="line"></span>
            <span class="line"></span>
          </div>

        </div>
     
      </div>
    </div>
   
  
  <div class="nav-full-width-2"> 
    <div class="container">
      <div id="nav">
        <ul class="main-nav">
          {% if user.is_authenticated %}
            <li><a href="{% url 'blog:main-view' %}">Home</a></li>
            <li><a href="{% url 'blog:myrecipes-view' %}">My Recipes</a></li>
            <li><a href="{% url 'blog:create-recipe' %}">Create Recipe</a></li>
            <li><a href="{% url 'blog:draft-view' %}">Drafts</a></li>
            <li class="categories-btn1"><a href="#">Categories</a></li>
            <!-- <li><a href="#">About</a></li> -->
          {% else %}
            <li><a href="{% url 'accounts:login-view' %}">Home</a></li>
            <li><a class="categories-btn1" href="#">Categories</a></li>  
            <!-- <li><a href="{% url 'blog:about-view' %}">About</a></li> -->
          {% endif %}
          

         
        </ul>
    
        <ul class="socials">

          {% if user.is_authenticated %}

            <li>Logged in as: <a href="#" style="color: tomato; font-size: 13px;">{{ request.user.username }}</a></li>
            <li><a href="{% url 'accounts:profile-detail-view' request.user.profile.slug %}">Profile</a></li>
            <li><a href="{% url 'accounts:edit-profile' %}">Edit Profile</a></li>
            <li><a href="{% url 'accounts:logout-view' %}">Logout</a></li>
          {% else %}
            <li><a href="#">
              <i class="fab fa-instagram navbar-social"></i>
            </a></li>
            <li><a href="#">
              <i class="fab fa-facebook navbar-social"></i>
            </a></li>
            <li><a href="#">
              <i class="fab fa-pinterest navbar-social"></i>
            </a></li>

          {% endif %}
        </ul>

        

      </div>
    </div>
  </div>



    <!-- NAVBAR MOBILE -->



    <div class="navbar-mobile">

      <div class="user">
        <p>Logged in as: <a href="#" style="color: tomato; font-size: 13px;">{{ request.user.username }}</a></p>
      </div>

      <div class="right search">
        <form action="{% url 'blog:search-recipes' %}" method="POST">
          {% csrf_token %}
          <input type="text" placeholder="Search Recipes" name="searched">
          <button type="submit" class="search-btn">Search</button>
        </form>
      </div>

      <ul>
        {% if user.is_authenticated %}
          <a href="{% url 'blog:main-view' %}"><li>Home</li></a>
          <a href="{% url 'blog:myrecipes-view' %}"><li>My Recipes</li></a>
          <a href="{% url 'blog:create-recipe' %}"><li>Create Recipe</li></a>
          <a href="{% url 'blog:draft-view' %}"><li>Drafts</li></a>
          <a class="categories-btn2" href="#"><li>Categories</li></a>
          <!-- <a href="#"><li>About</li></a> -->
          <a href="{% url 'accounts:profile-detail-view' request.user.profile.slug %}"><li>Profile</li></a>
          <a href="{% url 'accounts:edit-profile' %}"><li>Edit Profile</li></a>
          <a href="{% url 'accounts:logout-view' %}"><li>Logout</li></a>
        {% else %}
          <a href="{% url 'blog:main-view' %}"><li>Home</li></a>
          <a class="categories-btn2" href="#"><li>Categories</li></a>
          <!-- <a href="#"><li>About</li></a> -->
          <a href="{% url 'blog:main-view' %}"><li>Login</li></a>

          <div class="nav-mobile-socials">
            <a href="#">
            <i class="fab fa-instagram navbar-social"></i>
            </a>

            <a href="#">
              <i class="fab fa-facebook navbar-social"></i>
            </a>
            
            <a href="#">
              <i class="fab fa-pinterest navbar-social"></i>
            </a>

        </div>

        {% endif %}
        
      </ul>
    </div>
</header>
  <!-- END NAV -->