accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (
  login_view, 
  register_view, 
  profile_detail_view,
  logout_view,
  edit_profile
)
app_name = 'accounts'

urlpatterns = [
  path('', login_view, name='login-view'),





  path('accounts/logout/', logout_view, name='logout-view'),
  path('accounts/register/', register_view, name='register'),
  path('accounts/edit-profile/', edit_profile, name='edit-profile'),
  path('accounts/<slug>/', profile_detail_view, name='profile-detail-view'),

  

  

]

# Password reset 
# 1 - submit email form 
# 2 - email sent success message
# 3 - link to password reset form in email
# 4 - Passwrod successfully change message

blog/urls.py
from django.urls import path
from .views import (
  home_view, 
  my_recipes_view,
  create_recipe,
  main_view,
  recipe_detail,
  edit_recipe,
  delete_recipe,
  draft_view, 
  edit_recipe_draft,
  delete_recipe_draft,
  search_recipes,
  category_view,
  about_view,
)

app_name = 'blog'

urlpatterns = [
  path('', main_view, name='main-view'),
  path('myrecipes/', my_recipes_view, name='myrecipes-view'),
  path('create-recipe/', create_recipe, name='create-recipe'),
  path('recipe-detail/<slug>/', recipe_detail, name='recipe-detail'),
  path('edit-recipe/<slug>/', edit_recipe, name='edit-recipe'),
  path('delete-recipe/<slug>/', delete_recipe, name='delete-recipe'),
  path('draft-view/', draft_view, name='draft-view'),

  path('edit-draft/<slug>', edit_recipe_draft, name='edit-draft'),
  path('delete-draft/<slug>', delete_recipe_draft, name='delete-draft'),
  path('search-recipes/', search_recipes, name='search-recipes'),
  path('category/<cats>/', category_view, name='category-view'),
  path('about/', about_view, name='about-view'),
  #path('rate-recipe/slug/', rate, name='rate-recipe'),
  #path('submit-review/<int:recipe_id>/', submit_review, name='submit-review'),
]

myrecipe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .forms import UserPasswordResetForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),

#password reset
  path('reset_password/', 
    auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        form_class=UserPasswordResetForm,
        ), 
    name='reset_password'),

  path('reset_password_sent/', 
    auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'), 
    name='password_reset_done'),

  path('reset/<uidb64>/<token>', 
    auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'), 
    name='password_reset_confirm'),

  path('reset_password_complete/', 
    auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'), 
    name='password_reset_complete'),

    path('blog/', include('blog.urls', namespace='blog')),

    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Profile
from ckeditor.fields import RichTextField
from django.urls import reverse

from django.template.defaultfilters import slugify
from .utils import get_random_code
from django.db.models import Avg

from django.core.validators import MaxValueValidator, MinValueValidator

class Category(models.Model):
  name = models.CharField(max_length=100)
  image = models.ImageField(upload_to='categories/')

  def __str__(self):
    return self.name
  
  class Meta:
    verbose_name = "Category"
    verbose_name_plural = "Categories"
  

  def get_url(self):
    #from urls.py, blog/category/category_name
    return reverse('blog:category-view', args=[self.name] )

OPTIONS = (
  #db       frontend/admin
  ('draft', 'Draft'),
  ('published', 'Published'),
)

class NewManager(models.Manager):
  #custom queryset
  def get_queryset(self):
    return super().get_queryset().filter(status='published')

class Post(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    photo = models.ImageField(default='noimage.jpg', upload_to='posts/', null=True, blank=True)
    cooking_time = models.CharField(max_length=50, blank=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')
    description = models.CharField(max_length=500, null=True, blank=True)
    content = RichTextField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    liked = models.ManyToManyField(Profile, blank=True, related_name='likes')
    status = models.CharField(max_length=10, choices=OPTIONS, default='draft')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    featured = models.BooleanField()

    objects = models.Manager() #default manager
    newmanager = NewManager() #custom manager

    class Meta:
      ordering = ('-created',)


    def __str__(self):
        return self.title
    
    def average_review(self):
      reviews = Review.objects.filter(recipe=self).aggregate(average=Avg('rate'))
      avg = 0
      if reviews['average'] is not None:
        avg = float(reviews['average'])
      return avg
    
    def count_review(self):
      count_review = Review.objects.filter(recipe=self).count()
      return count_review
    
  

    
    #generate slug
    def save(self, *args, **kwargs):
      ex = False

      #if title is filled out
      if self.title:
        to_slug = slugify(str(self.title))

        #return true
        ex = Post.objects.filter(slug=to_slug).exists()

        #if slug already exists
        while ex:
          to_slug = slugify(to_slug + " " + str(get_random_code()))
          ex = Post.objects.filter(slug=to_slug).exists()

      #if title blank
      else:
        to_slug = str(self.title)

      self.slug = to_slug
      super().save(*args, **kwargs)
    

    @property
    def get_reviews(self):
      # Post.reviews.all(), reviews->from Post related name in Review model
      return self.reviews.all().order_by('-timestamp')
    

RATE_CHOICES = [
  (1, '1 - Bad'),
  (2, '2 - Poor'),
  (3, '3 - Average'),
  (4, '4 - Great'),
  (5, '5 - Excellent'),
]

class Review(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  recipe = models.ForeignKey(Post, related_name='reviews', on_delete=models.CASCADE)
  timestamp = models.DateTimeField(auto_now_add=True)
  content = models.TextField()
  #rate = models.PositiveSmallIntegerField(choices=RATE_CHOICES, blank=True)
  rate = models.FloatField()
  # rate = models.IntegerField(default=0, validators=[
  #   MaxValueValidator(5),
  #   MinValueValidator(0),
  # ])

  def __str__(self):
      return str(self.user)
  

  

  # def count_review()

blog/forms.py
from django import forms
from .models import Post, Review, RATE_CHOICES


class CreateRecipeForm(forms.ModelForm):
  # featured = forms.BooleanField(widget=forms.RadioSelect(attrs={'class': 'featured-radio-btn'}))
  class Meta:
    model = Post
    fields = ('title', 'photo', 'cooking_time', 'description', 'content', 'category', 'status', 'featured')
    #exclude = ('author', 'liked', 'updated', 'created')

class EditRecipeForm(forms.ModelForm):
  class Meta:
    model = Post
    exclude = ('author', 'liked', 'updated', 'created', 'slug')

class EditDraftForm(forms.ModelForm):
  class Meta:
    model = Post
    fields = ('status',)

class RateForm(forms.ModelForm):
  #content = forms.CharField(widget=forms.Textarea(attrs={'class': 'review-content'}), required=False)
  # rate = forms.ChoiceField(choices=RATE_CHOICES, widget=forms.Select(attrs={'class': 'review-rate'}), required=True)


  class Meta:
    model = Review
    fields = ('content', 'rate')
  
  # def clean(self):
  #   cleaned_data = super().clean()
  #   rate = cleaned_data.get("rating")

myrecipe/forms.py
from django.contrib.auth.forms import PasswordResetForm
from django import forms

class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordResetForm, self).__init__(*args, **kwargs)
    
    email = forms.EmailField(label='', widget=forms.EmailInput(attrs={
        'class': 'password-reset-email',
        'placeholder': 'Your Email',
        'type': 'email',
        'name': 'email'
        }))

blog/views.py
from django.shortcuts import render, redirect
from .forms import CreateRecipeForm, EditRecipeForm, EditDraftForm, RateForm
from accounts.models import Profile
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import Post, Category, Review
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import AnonymousUser


def home_view(request):
  return render(request, 'blog/home.html')

def about_view(request):
  return render(request, 'blog/about.html')


@login_required(login_url="/")
def main_view(request):
  recipes = Post.objects.filter(status='published')

  context = {
    'recipes': recipes,
    }
  
  return render(request, 'blog/home.html', context)


def recipe_detail(request, slug):
  
  recipe = get_object_or_404(Post, slug=slug)
  profile_image = recipe.author.avatar.url
  profile_name = recipe.author.user
  user = request.user 
  user1 = request.user 

  
  #Check if you submitted a review on a recipe already
  is_reviewed = False

  
  recipe_user = ''
  test = Review.objects.filter(recipe=recipe)
  for t in test:
    recipe_user = t.user
    #print(t.recipe)
  
  if request.method == 'POST':
    form = RateForm(request.POST)

    rating = request.POST['rating']
    content = request.POST['content']


    obj = Review.objects.create(
      content=content,
      rate=rating,
      user=user,
      recipe=recipe
    )
    obj.save()
    print('success')
    return redirect('blog:recipe-detail', slug=recipe.slug)
  else:
    print('failed')



  #review form
  # if request.method == 'POST':
  #   rate_form = RateForm(request.POST)
  #   if rate_form.is_valid():
  #     rate = rate_form.save(commit=False)
  #     rate.user = user
  #     rate.recipe = recipe
  #     rate.save()
  #     return redirect('blog:recipe-detail', slug=slug)
  # else:
  #   rate_form = RateForm()


  # if request.method == 'POST':
  #   form = RateForm(request.POST or None)
  #   if form.is_valid():
  #     data = form.save(commit=False)
  #     data.rate = form.cleaned_data['rating']
  #     data.content = form.cleaned_data['content']
  #     data.recipe_id = recipe.id
  #     data.user_id = request.user.id
  #     data.save()
  #     return redirect('recipe-detail', slug=recipe.slug)
  #   else:
  #     print('failed')

  context = {
    'recipe': recipe,
    'profile_image': profile_image,
    'profile_name': profile_name,
    #'rate_form': rate_form,
    'is_reviewed': is_reviewed,
    'test': test,
    'recipe_user': recipe_user,
    #'get_count_review': get_count_review,

  }

  
  return render(request, 'blog/recipe_detail.html', context)



# def submit_review(request, recipe_id):
#   #current url
#   url = request.META.get('HTTP_REFERER')

#   if request.method == 'POST':
#     form = RateForm(request.POST)
#     if form.is_valid():
#       data = Review()
#       data.rate = form.cleaned_data['rating']
#       data.content = form.cleaned_data['content']
#       data.recipe_id = recipe_id
#       data.user_id = request.user.id
#       data.save()
#       return redirect(url)




@login_required(login_url="/")
def my_recipes_view(request):
  profile = Profile.objects.get(user=request.user)
  myrecipes = Post.objects.filter(author=profile)
  published_recipe = Post.objects.filter(Q(status='published') & Q(author=profile))
  

  context = {
    'myrecipes': myrecipes,
    'published_recipe': published_recipe,
    }
  return render(request, 'blog/my_recipes.html', context)



@login_required(login_url="/")
def create_recipe(request):
  profile = Profile.objects.get(user=request.user)
  print(profile)

  if request.method == 'POST':
    create_recipe_form = CreateRecipeForm(request.POST, request.FILES)

    if create_recipe_form.is_valid():
      instance = create_recipe_form.save(commit=False)
      instance.author = profile
      instance.save()

      print('succes created')
      # messages.success(request, 'Recipe Created')
      return redirect('blog:create-recipe')
    else:
      print('failed')
  else:
    create_recipe_form = CreateRecipeForm()

  context = {
    'create_recipe_form': create_recipe_form,
  }
      
  return render(request, 'blog/create_recipe.html', context)


@login_required(login_url="/")
def edit_recipe(request, slug):
  # profile = Profile.objects.get(user=request.user)
  # recipe = Post.objects.get(author=profile)

  recipe = get_object_or_404(Post, slug=slug)

  if request.method == 'POST':
    edit_recipe_form = EditRecipeForm(request.POST, request.FILES, instance=recipe)
    
    if edit_recipe_form.is_valid():
      edit_recipe_form.save()
      return redirect('blog:myrecipes-view')
  else:
    edit_recipe_form = EditRecipeForm(instance=recipe)
  
  context = {
    'edit_recipe_form': edit_recipe_form
  }

  return render(request, 'blog/edit_recipe.html', context)

def delete_recipe(request, slug):
  recipe = get_object_or_404(Post, slug=slug)

  if request.method == 'POST':
    recipe.delete()
    return redirect('blog:myrecipes-view')

  context = {'recipe': recipe}
  return render(request, 'blog/delete_recipe.html', context)

@login_required(login_url="/")
def draft_view(request):
  recipe_draft = ''
  if request.method == 'POST':
    profile = Profile.objects.get(user=request.user)
    searched_draft = request.POST['searched-draft']
    searched_recipe_draft = Post.objects.filter(Q(title__contains=searched_draft) & Q(status='draft') & Q(author=profile))

    searched_count = searched_recipe_draft.count()

    context = {
      'searched_draft': searched_draft,
      'searched_recipe_draft': searched_recipe_draft,
      'searched_count': searched_count,
    }
   
    
    return render(request, 'blog/draft_view.html', context)
  else:
    profile = Profile.objects.get(user=request.user)
    recipe_draft = Post.objects.filter(Q(status='draft') & Q(author=profile))
    recipe_draft_count = recipe_draft.count()

    context = {
      'recipe_draft': recipe_draft,
      'recipe_draft_count': recipe_draft_count,
    }
  return render(request, 'blog/draft_view.html', context)


@login_required(login_url="/")
def edit_recipe_draft(request, slug):
  recipe = get_object_or_404(Post, slug=slug)

  if request.method == 'POST':
    edit_draft_form = EditDraftForm(request.POST, instance=recipe)
    
    if edit_draft_form.is_valid():
      edit_draft_form.save()
      return redirect('blog:draft-view')
  else:
    edit_draft_form = EditDraftForm(instance=recipe)
  
  context = {
    'edit_recipe_form': edit_draft_form,
    'recipe': recipe,
  }

  return render(request, 'blog/edit_draft.html', context)

@login_required(login_url="/")
def delete_recipe_draft(request, slug):
  recipe = get_object_or_404(Post, slug=slug)

  if request.method == 'POST':
      recipe.delete()
      return redirect('blog:draft-view')

  context = {
      'recipe': recipe
  }
  return render(request, 'blog/delete_draft.html', context)


def search_recipes(request):
  #recipes = Post.objects.filter(status='published')

  if request.method == 'POST':
    searched = request.POST['searched']
    recipes = Post.objects.filter(Q(title__contains=searched) & Q(status='published'))

    searched_count = recipes.count()

    context = {
      'searched': searched,
      'recipes': recipes,
      'searched_count': searched_count,
    }
    
    return render(request, 'blog/search.html', context)
  else:
    return render(request, 'blog/search.html')

def category_view(request, cats):
  category_recipes = Post.objects.filter(Q(category__name=cats) & Q(status='published'))
  category = Category.objects.filter(name=cats)[0]

  context = {
    'cats': cats,
    'category_recipes': category_recipes,
    'category': category,

  }
  return render(request, 'blog/categories.html', context)

blog/templates/blog/about.html
{% extends 'base.html' %}



{% block content %}
<div class="main-page-header">
  <div class="container">
    <div id="register-page">
      
      

      <div style="background: #fff; padding: 3rem 5rem;">
        <p>Developed by: Cristian To-ong</p>
        <p>Technologies: HTML, CSS, Javascript, Django</p>
      </div>
     
        
      

    </div>
  </div>
</div>
{% endblock content %}
  

blog/templates/blog/delete_draft.html
{% extends 'base.html' %}



{% block content %}

  <div class="main-page-header">
  <div class="container">
    <div id="register-page">
      
      
      <!-- Register -->
        <div id="register-form">
            
            {% if messages %}
            
              {% for message in messages %}
              <div style="color: tomato;">{{ message }}</div>
              {% endfor %}

            {% endif %}
              
          
          <form action="{% url 'blog:delete-draft' recipe.slug %}" method="POST" id="register-main-form">
            {% csrf_token %}
            <h1>Delete Recipe</h1>

            <p>Are you sure you want to delete "{{ recipe }}"?</p>
            <br>
            <br>
            <div class="inputs2">
              <button type="submit" style="background: tomato;">Confirm Delete</button>
              <a class="cancel-btn" href="{% url 'blog:draft-view' %}">
                Cancel
              </a>
            </div>
            
          </form>
        </div>


    </div>
  </div>
</div>
{% endblock content %}
  

blog/templates/blog/draft_view.html
{% extends 'base.html' %}



{% block content %}
<div class="main-page-header">
  <div class="container">
    <div id="register-page">
      
      

      <div class="draft-page">
        <h1>Drafts</h1>
        <div class="search-table">
          
          {% if recipe_draft %}
              <h3>Draft List ({{recipe_draft_count}})</h3> 
          {% else %}
            <h3>Draft List ({{searched_count}})</h3> 
          {% endif %}
            
          
          <div class="search">
            <form method="POST">
            {% csrf_token %}
              <input type="text" placeholder="Search" name="searched-draft">
              <button type="submit">Search</button>
            </form>
          </div>
        </div>
        <div class="draft-table">
          <table id="draft-table">

            <tr class="header">
              <th>Title</th>
              <th>Photo</th>
              <th>Category</th>
              <th>Status</th>
              <th>Edit</th>
              <th>Delete</th>
            </tr>
          {% if recipe_draft %}
            {% for recipe in recipe_draft %}
            <tr>
              <td>{{ recipe.title }}</td>
              <td class="img-draft"><img src="{{ recipe.photo.url }}"></td>
              <td>{{recipe.category}}</td>
              <td>{{recipe.status}}</td>
              <td><a href="{% url 'blog:edit-draft' recipe.slug %}"><i class="far fa-edit"></i></a></td>
              <td><a href="{% url 'blog:delete-draft' recipe.slug %}"><i class="far fa-trash-alt"></i></a></td>
            </tr>
            {% endfor %}
          {% elif searched_recipe_draft %}
            {% for recipe in searched_recipe_draft %}
            <tr>
              <td>{{ recipe.title }}</td>
              <td class="img-draft"><img src="{{ recipe.photo.url }}"></td>
              <td>{{recipe.category}}</td>
              <td>{{recipe.status}}</td>
              <td><a href="{% url 'blog:edit-draft' recipe.slug %}"><i class="far fa-edit"></i></a></td>
              <td><a href="{% url 'blog:delete-draft' recipe.slug %}"><i class="far fa-trash-alt"></i></a></td>
            </tr>
            {% endfor %}
           {% else %}
          <h3 style="background: #fff; padding: 3rem 5rem;">No Drafts</h3>
          {% endif %}

          </table>
        </div>
      </div>

     
        
      

    </div>
  </div>
</div>
{% endblock content %}
  

blog/templates/blog/recipe_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load widget_tweaks %}


{% block title %}
  all recipes
{% endblock title %}


{% block content %}
    <!-- MAIN CONTENT -->
    <div class="container">
      <section id="recipe-detail">
    
        <div class="recipe-detail-cards">
          
          <div class="recipe-detail-card">
            <h1 class="recipe-title">{{ recipe.title | title }}</h1>

            <div class="recipe-detail-user">
              <div class="info">

                <a href="{% url 'accounts:profile-detail-view' recipe.author.slug %}">
                <div class="user-img">
                  <img src="{{ profile_image }}" alt="">
                </div>
                </a>

                <div class="user-info">
                  <h1>{{profile_name}}</h1>
                  <small>{{ recipe.created }}</small>
                </div>
              </div>

              <!-- if user logged in and post author == current user -->
              {% if user.is_authenticated and recipe.author.user == request.user %}
                <div class="action-btns">
                <a href="{% url 'blog:edit-recipe' recipe.slug %}">Edit Recipe</a>
                <a href="{% url 'blog:delete-recipe' recipe.slug %}">Delete Recipe</a>
              </div>
              {% endif %}


            </div>

            <div class="recipe-detail-img">
              <img src="{{ recipe.photo.url }}" alt="">
            </div>

            <div class="recipe-detail-under">
              <div class="cooking-time">
                <i class="far fa-clock"></i>
                <h4>{{recipe.cooking_time}}</h4>
                
              </div>
              <!-- <div class="like">
                <a href="#"><i class="far fa-thumbs-up"></i></a><h3>Like</h3>
              </div> -->
   

                <!-- <h1 style="font-family: 'Lato">{{recipe.average_review}}</h1> -->

                
                {% if recipe.average_review %}
                <div class="rating-star">
                  <span style="margin-right: 0.5rem; font-size: 1.1rem; color: tomato;">{{ recipe.average_review }}</span>
                  <span style="margin-right: 0.5rem;">
                    <i class="fa fa-star{% if recipe.average_review < 0.5 %}-o{% elif recipe.average_review >= 0.5 and recipe.average_review < 1 %}-half-alt {% endif %}"></i>
                    <i class="fa fa-star{% if recipe.average_review < 1.5 %}-o{% elif recipe.average_review >= 1.5 and recipe.average_review < 2 %}-half-alt {% endif %}"></i>
                    <i class="fa fa-star{% if recipe.average_review < 2.5 %}-o{% elif recipe.average_review >= 2.5 and recipe.average_review < 3 %}-half-alt {% endif %}"></i>
                    <i class="fa fa-star{% if recipe.average_review < 3.5 %}-o{% elif recipe.average_review >= 3.5 and recipe.average_review < 4 %}-half-alt {% endif %}"></i>
                    <i class="fa fa-star{% if recipe.average_review < 4.5 %}-o{% elif recipe.average_review >= 4.5 and recipe.average_review < 5 %}-half-alt {% endif %}"></i>

                  </span>
                  <span style="color: #787878;">({{ recipe.count_review }})</span>
                  
                </div>
                {% else %}
                  <div class="rating-star">
                    <span style="margin-right: 0.5rem;">
                      <i class="fa fa-star-o"></i>
                      <i class="fa fa-star-o"></i>
                      <i class="fa fa-star-o"></i>
                      <i class="fa fa-star-o"></i>
                      <i class="fa fa-star-o"></i>
                    </span>
                  </div>
                  <span>(0)</span>
                {% endif %}
                
                

            </div>

            <div class="recipe-detail-desc">
              <p>{{ recipe.description }}</p>
            </div>

            <div class="recipe-detail-content">
              <p>{{ recipe.content | safe }}</p>
            </div>

          </div>
  
        </div>

        <br>
        <br>
        

        <!-- REVIEWS -->
       
          <div class="reviews">
            
            {% if user.is_authenticated %}
              
              {% if recipe.author.user == request.user %}
                <h3>You can't submit review on your own recipe</h3>
              {% elif recipe_user == request.user %}
                <h3>You already submitted a review in this recipe.</h3>
              {% else %}
                
                <div class="review-form">
                  <h3>Leave a review</h3>
                  <br>
                  <form class="rate-form" method="POST" action="">
                    {% csrf_token %}
                    <label for=""></label>
                    <!-- {{rate_form.rate}} -->
                      
                    <!-- rating star -->
                    <div class="rate">
                      <input type="radio" name="rating" id="rating10" value="5" required><label for="rating10" title="5"></label>
                      <input type="radio" name="rating" id="rating9" value="4.5" required><label for="rating9" title="4.5" class="half"></label>
                      <input type="radio" name="rating" id="rating8" value="4" required><label for="rating8" title="4"></label>
                      <input type="radio" name="rating" id="rating7" value="3.5" required><label for="rating7" title="3.5" class="half"></label>
                      <input type="radio" name="rating" id="rating6" value="3" required><label for="rating6" title="3"></label>
                      <input type="radio" name="rating" id="rating5" value="2.5" required><label for="rating5" title="2.5" class="half"></label>
                      <input type="radio" name="rating" id="rating4" value="2" required><label for="rating4" title="2"></label>
                      <input type="radio" name="rating" id="rating3" value="1.5" required><label for="rating3" title="1.5" class="half"></label>
                      <input type="radio" name="rating" id="rating2" value="1" required><label for="rating2" title="1"></label>
                      <input type="radio" name="rating" id="rating1" value="0.5" required><label for="rating1" title="0.5" class="half"></label>
                    </div>
                    

                    <br>
                    <br>
                    <!-- {{rate_form.content}} -->
                    <textarea name="content" rows="4" class="review-content-field"></textarea>
                    <br>
                    <br>
                    <button type="submit" class="review-submit">Submit Review</button>
                  </form>
                </div>
              {% endif %}
              
                
          </div>
        {% else %}
          <a href="{% url 'accounts:login-view' %}" class="">Login to Review</a>

          
        {% endif %}

       
        
        <!-- DISPLAY REVIEWS -->
        <h1>Reviews:</h1> 
        <span>{{ recipe.count_review }} Reviews</span>
        {% for review in recipe.get_reviews %}
          <div class="user-reviews">
            <div class="left">

              <!-- recipe.author.slug -->

              <a href="{% url 'accounts:profile-detail-view' review.user.profile.slug %}">
              <div class="user-img">
                 <img src="{{ review.user.profile.avatar.url }}" alt="">
              </div>
              </a>
              
            </div>

            <div class="right">
              <div class="user-name">
                <p>{{ review.user.username }}</p>
                
              </div>

              <div class="rating">
                <div class="rate">
                  <!-- <p>Rating: <span style="font-weight: 600;">{{review.rate}}</span></p> -->
                  <div class="rating-star">
                    <span>
                      <i class="fa fa-star{% if review.rate == 0.5 %}-half-alt{% elif review.rate < 1 %}-o {% endif %}"></i>
                      <i class="fa fa-star{% if review.rate == 1.5 %}-half-alt{% elif review.rate < 2 %}-o {% endif %}"></i>
                      <i class="fa fa-star{% if review.rate == 2.5 %}-half-alt{% elif review.rate < 3 %}-o {% endif %}"></i>
                      <i class="fa fa-star{% if review.rate == 3.5 %}-half-alt{% elif review.rate < 4 %}-o {% endif %}"></i>
                      <i class="fa fa-star{% if review.rate == 4.5 %}-half-alt{% elif review.rate < 5 %}-o {% endif %}"></i>
                    </span>
                  </div>
                </div>
                <div><small style="color: #7A7A7E;">{{ review.timestamp|timesince }} ago</small></div>
              </div>

              <div class="content">
                <p>{{ review.content }}</p>
              </div>
            </div>
          </div>     
        {% endfor %}
          
     

        
      </section>
    </div>
    
{% endblock content %}
  